---
apiVersion: v1
kind: Service
metadata:
  name: redis-kn8435-test-service
  labels:
    username: kn8435
    env: test
spec:
  type: ClusterIP
  selector:
    app: kn8435-test-redis
  ports:
  - name: redis-kn8435-test-ports
    port: 6379
    targetPort: 6379
