---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-kn8435-test-deployment
  labels:
    app: kn8435-test-redis
    username: kn8435
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kn8435-test-redis
  template:
    metadata:
      labels:
        app: kn8435-test-redis
        username: kn8435
        env: test
    spec:
      containers:
        - name: redis500
          image: redis:5.0.0
          volumeMounts:
          - name: redis-kn8435-test-pvc
            mountPath: "/data"
      volumes:
      - name: redis-kn8435-test-pvc
        persistentVolumeClaim:
          claimName: redis-kn8435-data

