---
apiVersion: v1
kind: Service
metadata:
  name: flask-kn8435-test-service
  labels:
    username: kn8435
    env: test
spec:
  type: ClusterIP
  selector:
    app: kn8435-test-flask
  ports:
  - name: flask-kn8435-test-ports
    port: 5000
    targetPort: 5000
