---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-kn8435-test-pvc
  labels:
    username: kn8435
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
