---
apiVersion: v1
kind: Pod
metadata:
  name: hello-name-env
  labels:
    greeting: personalized
spec:
  containers:
    - name: hello-name-env
      image: ubuntu:18.04
      env: 
        - name: "Name"
          value: "Kyle"
      command: ['sh', '-c', 'echo "Hello, $Name" && sleep 3600']
