---
apiVersion: v1
kind: Pod
metadata:
  name: hello-name
  labels:
    greeting: personalized
spec:
  containers:
    - name: hello-name
      labels:
        greeting: personalized
      image: ubuntu:18.04
      command: ['sh', '-c', 'echo "Hello, $Name" && sleep 3600']
